from typing import List, Optional, Protocol

from src.warehouse.domain.rack import Rack
from src.warehouse.domain.store import Storing


class StoragesRepository(Protocol):
    def get(self, storing_id: str) -> Optional[Storing]: ...
    def add(self, storing: Storing) -> None: ...
    def update(self, storing: Storing) -> None: ...
    def list_all_storing(self) -> List[Storing]: ...


class RacksRepository(Protocol):
    def get(self, rack_id: str) -> Optional[Rack]: ...
    def add(self, rack: Rack) -> None: ...
    def update(self, rack: Rack) -> None: ...
    def list_all_racks(self) -> List[Rack]: ...
