from typing import List, Optional, Protocol

from src.warehouse.domain.store import Storing


class StoragesRepository(Protocol):
    def get(self, storing_id: str) -> Optional[Storing]: ...
    def add(self, reservation: Storing) -> None: ...
    def list_all_storing(self) -> List[Storing]: ...
